GET http://localhost:3000
 
###

POST http://localhost:3000/login
Content-Type: application/json

{
"email": "f@fd",
"password": "123"
}

###
DELETE http://localhost:3000/login


###
POST http://localhost:3000/register
Content-Type: application/json

{
"email": "f@fd",
"userName": "lulo",
"password": "123",
"password2": "123"
}
